services:
  - docker

before_install:
  - docker pull strebul/go-builder1.9.2-alpine3.6:latest

install:
  - docker run -v ${TRAVIS_BUILD_DIR}:/go/src/github.com/2at2/telegaacli -w /go/src/github.com/2at2/telegaacli strebul/go-builder1.9.2-alpine3.6:latest /bin/sh -c 'make deps && make ok && make build'
