language: "go"

go:
  - 1.9.2

os:
  - linux

services:
  - docker

before_install:
  - go get github.com/golang/lint/golint github.com/fzipp/gocyclo
  - make deps
  - make ok

script:
  - make build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker build -t strebul/telegacli:latest .;
    docker push strebul/telegacli:latest;
    fi
