language: "go"

go:
  - 1.9.2

os:
  - linux

services:
  - docker

before_install:
  - docker pull $BUILDER

script:
  - docker run -v $TRAVIS_BUILD_DIR:/go/src/github.com/2at2/telegacli -w /go/src/github.com/2at2/telegacli $BUILDER /bin/sh -c 'make deps && make ok && make build'
  - ls -l bin/

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t strebul/telegacli:latest . && docker push strebul/telegacli:latest;
    fi
  - if [ $(echo "$TRAVIS_BRANCH" | cut -c 1-7) == "release" ]; then
    export tag=$(echo "$TRAVIS_BRANCH" | cut -c 9-)
    docker build -t strebul/telegacli:$tag . && docker push strebul/telegacli:$tag;
    fi

