language: "go"

go:
  - 1.9.2

os:
  - linux

before_install:
  - go get github.com/golang/lint/golint github.com/fzipp/gocyclo
  - make deps
  - make ok

script:
  - make build

before_deploy:
  - docker build -t strebul/telegacli:latest .

deploy:
  - docker push strebul/telegacli:latest
